Adjust "title-from-url" command

diff --git a/title-from-url b/title-from-url
--- a/title-from-url
+++ b/title-from-url
@@ -1,6 +1,7 @@
 #!/bin/zsh
 
 if [ $# -ne 1 ]; then echo 'Please specify the URL' 1>&2; exit 1; fi
-docker run --rm webpage-title $1
+if ! which docker >& /dev/null; then echo 'Docker not found' 1>&2; exit 1; fi
+docker run --rm atton/webpage-title $1
 
 # vim: set filetype=zsh :
